CREATE TABLE IF NOT EXISTS SCHEDULE
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    TODO VARCHAR(255) NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS USER
(
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USERNAME, PASSWORD)
);

ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_FK_USERNAME_PASSWORD FOREIGN KEY (USERNAME, PASSWORD) REFERENCES USER (USERNAME, PASSWORD) ON DELETE CASCADE ON UPDATE CASCADE;
